sync_thies_files:
  name: "Synchronize Thies Files"
  description: "Initiates file synchronization with the FTP server and cloud storage."
  fields: {}

sync_local_backup:
  name: "Execute Local backup for extracted files"
  description: "Initiates a file backup which are uploaded in Filebrowser and moved to Sharepoint folder "
  fields: {}

get_camera_time_rates:
  name: "Get Camera Time Rates"
  description: "Retrieve time rates for photo capture and video recording from connected network cameras"
  fields:
    latitude: 
      name: Latitude
      required: true
      selector:
        number:
          min: -90
          max: 90
          step: 0.000001
    longitude:
      name: Longitude
      required: true
      selector:
        number:
          min: -180
          max: 180
          step: 0.000001
