sync_thies_files:
  name: "Synchronize Thies Files"
  description: "Initiates file synchronization with the FTP server and cloud storage."
  fields: {}

sync_local_backup:
  name: "Execute Local backup for extracted files"
  description: "Initiates a file backup which are uploaded in Filebrowser and moved to Sharepoint folder "
  fields: {}

get_netcamera_rates:
  name: "Get Camera Time Rates"
  description: "Retrieve time rates for photo capture and video recording from connected network cameras"
  fields:
    latitude:
      name: Latitude
      required: true
      selector:
        number:
          min: -90
          max: 90
    longitude:
      name: Longitude
      required: true
      selector:
        number:
          min: -180
          max: 180

update_task:
  name: Update a Discord Task
  description: Saviia provides this action for updating a message that had been sent in a Discord Channel
  fields:
    task:
      name: Task payload to update the Discord message
      required: true
      selector:
        object:
    completed:
      name: Completed attribute which defines if the Task was finished.
      required: true
      selector:
        boolean:

delete_task:
  name: Delete a Discord Task
  description: Saviia provides this action for deleting a message that had been sent in a Discord Channel
  fields:
    task_id:
      name: Task ID from Discord webhook channel
      required: true
      selector:
        text:

create_task:
  name: "Create Task"
  description: "Create a new task and send it to Discord via webhook"
  fields:
    task:
      name: Task payload
      required: true
      selector:
        object:
    images:
      name: Images
      description: "Base64 encoded images to attach"
      required: false

get_tasks:
  name: "Get Tasks"
  description: "Retrieves a list of tasks based on the provided parameters."
  fields:
    params:
      name: Parameters
      required: false
      selector:
        object: